var searchData=
[
  ['saveclientdetails_0',['SaveClientDetails',['../class_scored_productions_1_1_twitch_unite_1_1_save_client_details.html',1,'ScoredProductions::TwitchUnite']]],
  ['searchcategories_1',['SearchCategories',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_search_1_1_search_categories.html',1,'ScoredProductions::TwitchUnite::API::Search']]],
  ['searchchannels_2',['SearchChannels',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_search_1_1_search_channels.html',1,'ScoredProductions::TwitchUnite::API::Search']]],
  ['secrets_3',['Secrets',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_extensions_1_1_i_extensions_1_1_secrets.html',1,'ScoredProductions::TwitchUnite::API::Extensions::IExtensions']]],
  ['segment_4',['Segment',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_schedule_1_1_i_schedule_1_1_segment.html',1,'ScoredProductions::TwitchUnite::API::Schedule::ISchedule']]],
  ['sendashoutout_5',['SendAShoutout',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_chat_1_1_send_a_shoutout.html',1,'ScoredProductions::TwitchUnite::API::Chat']]],
  ['sendchatannouncement_6',['SendChatAnnouncement',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_chat_1_1_send_chat_announcement.html',1,'ScoredProductions::TwitchUnite::API::Chat']]],
  ['sendextensionchatmessage_7',['SendExtensionChatMessage',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_extensions_1_1_send_extension_chat_message.html',1,'ScoredProductions::TwitchUnite::API::Extensions']]],
  ['sendextensionpubsubmessage_8',['SendExtensionPubSubMessage',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_extensions_1_1_send_extension_pub_sub_message.html',1,'ScoredProductions::TwitchUnite::API::Extensions']]],
  ['sendgueststarinvite_9',['SendGuestStarInvite',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_send_guest_star_invite.html',1,'ScoredProductions::TwitchUnite::API::Guest_Star']]],
  ['sendwhisper_10',['SendWhisper',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_whispers_1_1_send_whisper.html',1,'ScoredProductions::TwitchUnite::API::Whispers']]],
  ['session_11',['Session',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_web_socket_messages_1_1_session.html',1,'ScoredProductions::TwitchUnite::EventSub::WebSocketMessages']]],
  ['setextensionconfigurationsegment_12',['SetExtensionConfigurationSegment',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_extensions_1_1_set_extension_configuration_segment.html',1,'ScoredProductions::TwitchUnite::API::Extensions']]],
  ['setextensionrequiredconfiguration_13',['SetExtensionRequiredConfiguration',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_extensions_1_1_set_extension_required_configuration.html',1,'ScoredProductions::TwitchUnite::API::Extensions']]],
  ['shieldmodebegin_14',['ShieldModeBegin',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_shield_mode_begin.html',1,'ScoredProductions::TwitchUnite::EventSub::Events']]],
  ['shieldmodeend_15',['ShieldModeEnd',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_shield_mode_end.html',1,'ScoredProductions::TwitchUnite::EventSub::Events']]],
  ['shoutoutcreate_16',['ShoutoutCreate',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_shoutout_create.html',1,'ScoredProductions::TwitchUnite::EventSub::Events']]],
  ['shoutoutreceived_17',['ShoutoutReceived',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_shoutout_received.html',1,'ScoredProductions::TwitchUnite::EventSub::Events']]],
  ['singletoninstance_18',['SingletonInstance',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['singletoninstance_3c_20debugmanager_20_3e_19',['SingletonInstance&lt; DebugManager &gt;',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['singletoninstance_3c_20twitchapiclient_20_3e_20',['SingletonInstance&lt; TwitchAPIClient &gt;',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['singletoninstance_3c_20twitchbadgemanager_20_3e_21',['SingletonInstance&lt; TwitchBadgeManager &gt;',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['singletoninstance_3c_20twitchemotemanager_20_3e_22',['SingletonInstance&lt; TwitchEmoteManager &gt;',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['singletoninstance_3c_20twitcheventsubclient_20_3e_23',['SingletonInstance&lt; TwitchEventSubClient &gt;',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['singletoninstance_3c_20twitchircclient_20_3e_24',['SingletonInstance&lt; TwitchIRCClient &gt;',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['singletoninstance_3c_20twitchmessageatlasmanager_20_3e_25',['SingletonInstance&lt; TwitchMessageAtlasManager &gt;',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['size_26',['Size',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_bits_1_1_i_bits_1_1_size.html',1,'ScoredProductions::TwitchUnite::API::Bits::IBits']]],
  ['snoozenextad_27',['SnoozeNextAd',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_ads_1_1_snooze_next_ad.html',1,'ScoredProductions::TwitchUnite::API::Ads']]],
  ['socketresponse_28',['SocketResponse',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_web_socket_messages_1_1_socket_response.html',1,'ScoredProductions::TwitchUnite::EventSub::WebSocketMessages']]],
  ['startaraid_29',['StartARaid',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_raids_1_1_start_a_raid.html',1,'ScoredProductions::TwitchUnite::API::Raids']]],
  ['startcommercial_30',['StartCommercial',['../struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_ads_1_1_start_commercial.html',1,'ScoredProductions::TwitchUnite::API::Ads']]],
  ['streamoffline_31',['StreamOffline',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_stream_offline.html',1,'ScoredProductions::TwitchUnite::EventSub::Events']]],
  ['streamonline_32',['StreamOnline',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_stream_online.html',1,'ScoredProductions::TwitchUnite::EventSub::Events']]],
  ['stringextensions_33',['StringExtensions',['../class_scored_productions_1_1_twitch_unite_1_1_utility_1_1_string_extensions.html',1,'ScoredProductions::TwitchUnite::Utility']]],
  ['sub_34',['Sub',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_chat_notification_1_1_sub.html',1,'ScoredProductions::TwitchUnite::EventSub::Events::ChannelChatNotification']]],
  ['subgift_35',['SubGift',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_chat_notification_1_1_sub_gift.html',1,'ScoredProductions::TwitchUnite::EventSub::Events::ChannelChatNotification']]],
  ['subscription_36',['Subscription',['../struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_web_socket_messages_1_1_subscription.html',1,'ScoredProductions::TwitchUnite::EventSub::WebSocketMessages']]]
];
