var _channel_subscription_end_8cs =
[
    [ "ScoredProductions.TwitchLinked.EventSub.Events.ChannelSubscriptionEnd", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_events_1_1_channel_subscription_end.html", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_events_1_1_channel_subscription_end" ]
];