var _channel_points_custom_reward_remove_8cs =
[
    [ "ScoredProductions.TwitchLinked.EventSub.Events.ChannelPointsCustomRewardRemove", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_remove.html", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_remove" ]
];