var _create_channel_stream_schedule_segment_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.Schedule.CreateChannelStreamScheduleSegment", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_schedule_1_1_create_channel_stream_schedule_segment.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_schedule_1_1_create_channel_stream_schedule_segment" ]
];