var _create_event_sub_subscription_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.EventSub.CreateEventSubSubscription", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_event_sub_1_1_create_event_sub_subscription.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_event_sub_1_1_create_event_sub_subscription" ]
];