var _get_authorization_code_token_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.Auth.GetAuthorizationCodeToken", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_auth_1_1_get_authorization_code_token.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_auth_1_1_get_authorization_code_token" ]
];