var _send_guest_star_invite_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.Guest_Star.SendGuestStarInvite", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_guest___star_1_1_send_guest_star_invite.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_guest___star_1_1_send_guest_star_invite" ]
];