var _set_extension_required_configuration_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.Extensions.SetExtensionRequiredConfiguration", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_extensions_1_1_set_extension_required_configuration.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_extensions_1_1_set_extension_required_configuration" ]
];