var _twitch_emote_manager_8cs =
[
    [ "ScoredProductions.TwitchLinked.ManagersAndBuilders.TwitchEmoteManager", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_emote_manager.html", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_emote_manager" ]
];