var _twitch_event_sub_subscriptions_8cs =
[
    [ "ScoredProductions.TwitchLinked.EventSub.TwitchEventSubSubscriptions", "class_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_twitch_event_sub_subscriptions.html", "class_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_twitch_event_sub_subscriptions" ]
];