var _update_channel_guest_star_settings_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.Guest_Star.UpdateChannelGuestStarSettings", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_guest___star_1_1_update_channel_guest_star_settings.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_guest___star_1_1_update_channel_guest_star_settings" ]
];