var _update_guest_star_slot_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.Guest_Star.UpdateGuestStarSlot", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_guest___star_1_1_update_guest_star_slot.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_guest___star_1_1_update_guest_star_slot" ]
];