var _update_drops_entitlements_8cs =
[
    [ "ScoredProductions.TwitchLinked.API.Entitlements.UpdateDropsEntitlements", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_entitlements_1_1_update_drops_entitlements.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_entitlements_1_1_update_drops_entitlements" ]
];