var _user_authorization_grant_8cs =
[
    [ "ScoredProductions.TwitchLinked.EventSub.Events.UserAuthorizationGrant", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_events_1_1_user_authorization_grant.html", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_events_1_1_user_authorization_grant" ]
];