var dir_30d5ef156a177c89c57afad2631a2c8c =
[
    [ "AddBlockedTerm.cs", "_add_blocked_term_8cs.html", "_add_blocked_term_8cs" ],
    [ "AddChannelModerator.cs", "_add_channel_moderator_8cs.html", "_add_channel_moderator_8cs" ],
    [ "AddChannelVIP.cs", "_add_channel_v_i_p_8cs.html", "_add_channel_v_i_p_8cs" ],
    [ "BanUser.cs", "_ban_user_8cs.html", "_ban_user_8cs" ],
    [ "CheckAutoModStatus.cs", "_check_auto_mod_status_8cs.html", "_check_auto_mod_status_8cs" ],
    [ "DeleteChatMessages.cs", "_delete_chat_messages_8cs.html", "_delete_chat_messages_8cs" ],
    [ "GetAutoModSettings.cs", "_get_auto_mod_settings_8cs.html", "_get_auto_mod_settings_8cs" ],
    [ "GetBannedUsers.cs", "_get_banned_users_8cs.html", "_get_banned_users_8cs" ],
    [ "GetBlockedTerms.cs", "_get_blocked_terms_8cs.html", "_get_blocked_terms_8cs" ],
    [ "GetModeratedChannels.cs", "_get_moderated_channels_8cs.html", "_get_moderated_channels_8cs" ],
    [ "GetModerators.cs", "_get_moderators_8cs.html", "_get_moderators_8cs" ],
    [ "GetShieldModeStatus.cs", "_get_shield_mode_status_8cs.html", "_get_shield_mode_status_8cs" ],
    [ "GetUnbanRequests.cs", "_get_unban_requests_8cs.html", "_get_unban_requests_8cs" ],
    [ "GetVIPs.cs", "_get_v_i_ps_8cs.html", "_get_v_i_ps_8cs" ],
    [ "IModeration.cs", "_i_moderation_8cs.html", "_i_moderation_8cs" ],
    [ "ManageHeldAutoModMessages.cs", "_manage_held_auto_mod_messages_8cs.html", "_manage_held_auto_mod_messages_8cs" ],
    [ "RemoveBlockedTerm.cs", "_remove_blocked_term_8cs.html", "_remove_blocked_term_8cs" ],
    [ "RemoveChannelModerator.cs", "_remove_channel_moderator_8cs.html", "_remove_channel_moderator_8cs" ],
    [ "RemoveChannelVIP.cs", "_remove_channel_v_i_p_8cs.html", "_remove_channel_v_i_p_8cs" ],
    [ "ResolveUnbanRequests.cs", "_resolve_unban_requests_8cs.html", "_resolve_unban_requests_8cs" ],
    [ "UnbanUser.cs", "_unban_user_8cs.html", "_unban_user_8cs" ],
    [ "UpdateAutoModSettings.cs", "_update_auto_mod_settings_8cs.html", "_update_auto_mod_settings_8cs" ],
    [ "UpdateShieldModeStatus.cs", "_update_shield_mode_status_8cs.html", "_update_shield_mode_status_8cs" ]
];