var namespace_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_hype___train =
[
    [ "GetHypeTrainEvents", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_hype___train_1_1_get_hype_train_events.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_hype___train_1_1_get_hype_train_events" ],
    [ "IHype_Train", "interface_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_hype___train_1_1_i_hype___train.html", "interface_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_hype___train_1_1_i_hype___train" ]
];