var namespace_scored_productions_1_1_twitch_linked_1_1_managers_and_builders =
[
    [ "EmoteExtensions", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_emote_extensions.html", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_emote_extensions" ],
    [ "TwitchBadge", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_badge.html", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_badge" ],
    [ "TwitchBadgeManager", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_badge_manager.html", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_badge_manager" ],
    [ "TwitchEmote", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_emote.html", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_emote" ],
    [ "TwitchEmoteManager", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_emote_manager.html", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_emote_manager" ],
    [ "TwitchMessageAtlasManager", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_message_atlas_manager.html", "class_scored_productions_1_1_twitch_linked_1_1_managers_and_builders_1_1_twitch_message_atlas_manager" ]
];