var namespace_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_polls =
[
    [ "ChannelPointsVoting", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_polls_1_1_channel_points_voting.html", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_polls_1_1_channel_points_voting" ],
    [ "Choices", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_polls_1_1_choices.html", "struct_scored_productions_1_1_twitch_linked_1_1_event_sub_1_1_polls_1_1_choices" ]
];