var namespace_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_charity =
[
    [ "GetCharityCampaign", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_charity_1_1_get_charity_campaign.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_charity_1_1_get_charity_campaign" ],
    [ "GetCharityCampaignDonations", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_charity_1_1_get_charity_campaign_donations.html", "struct_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_charity_1_1_get_charity_campaign_donations" ],
    [ "ICharity", "interface_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_charity_1_1_i_charity.html", "interface_scored_productions_1_1_twitch_linked_1_1_a_p_i_1_1_charity_1_1_i_charity" ]
];