var searchData=
[
  ['raid_0',['Raid',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_notification_1_1_raid.html',1,'ScoredProductions.StreamLinked.EventSub.Events.ChannelChatNotification.Raid'],['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_raid.html',1,'ScoredProductions.StreamLinked.EventSub.IChannel.Raid']]],
  ['removeblockedterm_1',['RemoveBlockedTerm',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_remove_blocked_term.html',1,'ScoredProductions::StreamLinked::API::Moderation']]],
  ['removechannelmoderator_2',['RemoveChannelModerator',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_remove_channel_moderator.html',1,'ScoredProductions::StreamLinked::API::Moderation']]],
  ['removechannelvip_3',['RemoveChannelVIP',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_remove_channel_v_i_p.html',1,'ScoredProductions::StreamLinked::API::Moderation']]],
  ['reply_4',['Reply',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_message_1_1_reply.html',1,'ScoredProductions::StreamLinked::EventSub::Events::ChannelChatMessage']]],
  ['resolveunbanrequests_5',['ResolveUnbanRequests',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_resolve_unban_requests.html',1,'ScoredProductions::StreamLinked::API::Moderation']]],
  ['resub_6',['Resub',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_notification_1_1_resub.html',1,'ScoredProductions::StreamLinked::EventSub::Events::ChannelChatNotification']]],
  ['retrievalsettings_7',['RetrievalSettings',['../class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_device_code_grant_flow_1_1_retrieval_settings.html',1,'ScoredProductions::StreamLinked::API::AuthContainers::DeviceCodeGrantFlow']]],
  ['reward_8',['Reward',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channel___points_1_1_i_channel___points_1_1_reward.html',1,'ScoredProductions.StreamLinked.API.Channel_Points.IChannel_Points.Reward'],['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_common_1_1_reward.html',1,'ScoredProductions.StreamLinked.EventSub.Common.Reward'],['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_points_automatic_reward_redemption_1_1_reward.html',1,'ScoredProductions.StreamLinked.EventSub.Events.ChannelPointsAutomaticRewardRedemption.Reward']]],
  ['roomstate_9',['ROOMSTATE',['../struct_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_tags_1_1_r_o_o_m_s_t_a_t_e.html',1,'ScoredProductions.StreamLinked.IRC.Tags.ROOMSTATE'],['../class_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_tags_1_1_twitch_i_r_c_tags_1_1_r_o_o_m_s_t_a_t_e.html',1,'ScoredProductions.StreamLinked.IRC.Tags.TwitchIRCTags.ROOMSTATE']]]
];
