var searchData=
[
  ['iads_0',['IAds',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads_1_1_i_ads.html',1,'ScoredProductions::StreamLinked::API::Ads']]],
  ['ianalytics_1',['IAnalytics',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_analytics_1_1_i_analytics.html',1,'ScoredProductions::StreamLinked::API::Analytics']]],
  ['iappaccesstoken_2',['IAppAccessToken',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_i_app_access_token.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['iauth_3',['IAuth',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_auth.html',1,'ScoredProductions::StreamLinked::API::Auth']]],
  ['iauthflow_4',['IAuthFlow',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_i_auth_flow.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['ibits_5',['IBits',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_bits_1_1_i_bits.html',1,'ScoredProductions::StreamLinked::API::Bits']]],
  ['iccls_6',['ICCLs',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_c_c_ls_1_1_i_c_c_ls.html',1,'ScoredProductions::StreamLinked::API::CCLs']]],
  ['ichannel_7',['IChannel',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_channel.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ichannel_5fpoints_8',['IChannel_Points',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channel___points_1_1_i_channel___points.html',1,'ScoredProductions::StreamLinked::API::Channel_Points']]],
  ['ichannelmessage_9',['IChannelMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_channel_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['ichannels_10',['IChannels',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channels_1_1_i_channels.html',1,'ScoredProductions::StreamLinked::API::Channels']]],
  ['icharity_11',['ICharity',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_charity_1_1_i_charity.html',1,'ScoredProductions::StreamLinked::API::Charity']]],
  ['icharitycampaign_12',['ICharityCampaign',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_charity_campaign.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ichat_13',['IChat',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_i_chat.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['iclips_14',['IClips',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_clips_1_1_i_clips.html',1,'ScoredProductions::StreamLinked::API::Clips']]],
  ['iconduits_15',['IConduits',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_conduits_1_1_i_conduits.html',1,'ScoredProductions::StreamLinked::API::Conduits']]],
  ['iconurls_16',['IconUrls',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_icon_urls.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['icustomreward_17',['ICustomReward',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_custom_reward.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ientitlements_18',['IEntitlements',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_entitlements_1_1_i_entitlements.html',1,'ScoredProductions::StreamLinked::API::Entitlements']]],
  ['ievent_19',['IEvent',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_event.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ieventsub_20',['IEventSub',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub_1_1_i_event_sub.html',1,'ScoredProductions::StreamLinked::API::EventSub']]],
  ['iextensions_21',['IExtensions',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_i_extensions.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['igames_22',['IGames',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_games_1_1_i_games.html',1,'ScoredProductions::StreamLinked::API::Games']]],
  ['igoals_23',['IGoals',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_goals_1_1_i_goals.html',1,'ScoredProductions.StreamLinked.API.Goals.IGoals'],['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_goals.html',1,'ScoredProductions.StreamLinked.EventSub.Interfaces.IGoals']]],
  ['iguest_5fstar_24',['IGuest_Star',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star.html',1,'ScoredProductions::StreamLinked::API::Guest_Star']]],
  ['ihype_5ftrain_25',['IHype_Train',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_hype___train_1_1_i_hype___train.html',1,'ScoredProductions::StreamLinked::API::Hype_Train']]],
  ['ihypetrain_26',['IHypeTrain',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_hype_train.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ijsonrequest_27',['IJsonRequest',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_json_request.html',1,'ScoredProductions::StreamLinked::API']]],
  ['image_28',['Image',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_image.html',1,'ScoredProductions::StreamLinked::EventSub::Events::Objects']]],
  ['imageblock_29',['ImageBlock',['../struct_scored_productions_1_1_stream_linked_1_1_uni_gif_1_1_uni_gif_1_1_image_block.html',1,'ScoredProductions::StreamLinked::UniGif::UniGif']]],
  ['imagedatablock_30',['ImageDataBlock',['../struct_scored_productions_1_1_stream_linked_1_1_uni_gif_1_1_uni_gif_1_1_image_block_1_1_image_data_block.html',1,'ScoredProductions::StreamLinked::UniGif::UniGif::ImageBlock']]],
  ['imageheaderhelpers_31',['ImageHeaderHelpers',['../class_scored_productions_1_1_stream_linked_1_1_image_header_helpers.html',1,'ScoredProductions::StreamLinked']]],
  ['images_32',['Images',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_images.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['imoderation_33',['IModeration',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_i_moderation.html',1,'ScoredProductions::StreamLinked::API::Moderation']]],
  ['implicitgrantflow_34',['ImplicitGrantFlow',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_implicit_grant_flow.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['implicitgrantflowsettings_35',['ImplicitGrantFlowSettings',['../class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_setting_containers_f7cb81143b43499e7b658e50b5fc72c3.html',1,'ScoredProductions::StreamLinked::API::AuthContainers::SettingContainers']]],
  ['inoresponse_36',['INoResponse',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_no_response.html',1,'ScoredProductions::StreamLinked::API']]],
  ['internalsettingsstore_37',['InternalSettingsStore',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_internal_settings_store.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['ioauthtoken_38',['IOAuthToken',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_i_o_auth_token.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['iparsedmessage_39',['IParsedMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_parsed_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['ipoll_40',['IPoll',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_poll.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ipolls_41',['IPolls',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_polls_1_1_i_polls.html',1,'ScoredProductions::StreamLinked::API::Polls']]],
  ['iprediction_42',['IPrediction',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_prediction.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ipredictions_43',['IPredictions',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_predictions_1_1_i_predictions.html',1,'ScoredProductions::StreamLinked::API::Predictions']]],
  ['iraids_44',['IRaids',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_raids_1_1_i_raids.html',1,'ScoredProductions::StreamLinked::API::Raids']]],
  ['irccommandtype_45',['IRCCommandType',['../class_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_extensions_1_1_i_r_c_command_type.html',1,'ScoredProductions::StreamLinked::IRC::Extensions']]],
  ['ischedule_46',['ISchedule',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_schedule_1_1_i_schedule.html',1,'ScoredProductions::StreamLinked::API::Schedule']]],
  ['iscope_47',['IScope',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_scopes_1_1_i_scope.html',1,'ScoredProductions::StreamLinked::API::Scopes']]],
  ['isearch_48',['ISearch',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search_1_1_i_search.html',1,'ScoredProductions::StreamLinked::API::Search']]],
  ['isendermessage_49',['ISenderMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_sender_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['ishared_50',['IShared',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_i_shared.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['ishield_51',['IShield',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_shield.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['istreams_52',['IStreams',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_streams_1_1_i_streams.html',1,'ScoredProductions::StreamLinked::API::Streams']]],
  ['isubscription_53',['ISubscription',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_subscription.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['isubscriptions_54',['ISubscriptions',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_subscriptions_1_1_i_subscriptions.html',1,'ScoredProductions::StreamLinked::API::Subscriptions']]],
  ['itagcontainer_55',['ITagContainer',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_container.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_56',['ITagMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20clearchat_2etags_20_3e_57',['ITagMessage&lt; CLEARCHAT.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20clearmsg_2etags_20_3e_58',['ITagMessage&lt; CLEARMSG.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20globaluserstate_2etags_20_3e_59',['ITagMessage&lt; GLOBALUSERSTATE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20notice_2etags_20_3e_60',['ITagMessage&lt; NOTICE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20privmsg_2etags_20_3e_61',['ITagMessage&lt; PRIVMSG.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20roomstate_2etags_20_3e_62',['ITagMessage&lt; ROOMSTATE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20usernotice_2etags_20_3e_63',['ITagMessage&lt; USERNOTICE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20userstate_2etags_20_3e_64',['ITagMessage&lt; USERSTATE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['iteams_65',['ITeams',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_teams_1_1_i_teams.html',1,'ScoredProductions::StreamLinked::API::Teams']]],
  ['itwitchapidataobject_66',['ITwitchAPIDataObject',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_twitch_a_p_i_data_object.html',1,'ScoredProductions::StreamLinked::API']]],
  ['itwitchapidataobjectextensions_67',['ITwitchAPIDataObjectExtensions',['../class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_twitch_a_p_i_data_object_extensions.html',1,'ScoredProductions::StreamLinked::API']]],
  ['itwitchircmessage_68',['ITwitchIRCMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_twitch_i_r_c_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['iuser_69',['IUser',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_user.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['iuseraccesstoken_70',['IUserAccessToken',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_i_user_access_token.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['iusermessage_71',['IUserMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_user_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['iusers_72',['IUsers',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_users_1_1_i_users.html',1,'ScoredProductions::StreamLinked::API::Users']]],
  ['ivideos_73',['IVideos',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_videos_1_1_i_videos.html',1,'ScoredProductions::StreamLinked::API::Videos']]],
  ['iwhispers_74',['IWhispers',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_whispers_1_1_i_whispers.html',1,'ScoredProductions::StreamLinked::API::Whispers']]],
  ['iwrapper_75',['IWrapper',['../interface_scored_productions_1_1_stream_linked_1_1_utility_1_1_interface_1_1_i_wrapper.html',1,'ScoredProductions::StreamLinked::Utility::Interface']]]
];
