var searchData=
[
  ['iads_0',['IAds',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads_1_1_i_ads.html',1,'ScoredProductions::StreamLinked::API::Ads']]],
  ['ianalytics_1',['IAnalytics',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_analytics_1_1_i_analytics.html',1,'ScoredProductions::StreamLinked::API::Analytics']]],
  ['iappaccesstoken_2',['IAppAccessToken',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_i_app_access_token.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['iauth_3',['IAuth',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_auth.html',1,'ScoredProductions::StreamLinked::API::Auth']]],
  ['iauthflow_4',['IAuthFlow',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_i_auth_flow.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['ibits_5',['IBits',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_bits_1_1_i_bits.html',1,'ScoredProductions::StreamLinked::API::Bits']]],
  ['iccls_6',['ICCLs',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_c_c_ls_1_1_i_c_c_ls.html',1,'ScoredProductions::StreamLinked::API::CCLs']]],
  ['ichannel_7',['IChannel',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_channel.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ichannel_5fpoints_8',['IChannel_Points',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channel___points_1_1_i_channel___points.html',1,'ScoredProductions::StreamLinked::API::Channel_Points']]],
  ['ichannels_9',['IChannels',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channels_1_1_i_channels.html',1,'ScoredProductions::StreamLinked::API::Channels']]],
  ['icharity_10',['ICharity',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_charity_1_1_i_charity.html',1,'ScoredProductions::StreamLinked::API::Charity']]],
  ['icharitycampaign_11',['ICharityCampaign',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_charity_campaign.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ichat_12',['IChat',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_i_chat.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['iclips_13',['IClips',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_clips_1_1_i_clips.html',1,'ScoredProductions::StreamLinked::API::Clips']]],
  ['iconduits_14',['IConduits',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_conduits_1_1_i_conduits.html',1,'ScoredProductions::StreamLinked::API::Conduits']]],
  ['iconurls_15',['IconUrls',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_icon_urls.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['icustomreward_16',['ICustomReward',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_custom_reward.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ientitlements_17',['IEntitlements',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_entitlements_1_1_i_entitlements.html',1,'ScoredProductions::StreamLinked::API::Entitlements']]],
  ['ievent_18',['IEvent',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_event.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ieventsub_19',['IEventSub',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub_1_1_i_event_sub.html',1,'ScoredProductions::StreamLinked::API::EventSub']]],
  ['iextensions_20',['IExtensions',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_i_extensions.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['igames_21',['IGames',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_games_1_1_i_games.html',1,'ScoredProductions::StreamLinked::API::Games']]],
  ['igoals_22',['IGoals',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_goals_1_1_i_goals.html',1,'ScoredProductions.StreamLinked.API.Goals.IGoals'],['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_goals.html',1,'ScoredProductions.StreamLinked.EventSub.Interfaces.IGoals']]],
  ['iguest_5fstar_23',['IGuest_Star',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star.html',1,'ScoredProductions::StreamLinked::API::Guest_Star']]],
  ['ihype_5ftrain_24',['IHype_Train',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_hype___train_1_1_i_hype___train.html',1,'ScoredProductions::StreamLinked::API::Hype_Train']]],
  ['ihypetrain_25',['IHypeTrain',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_hype_train.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ijsonrequest_26',['IJsonRequest',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_json_request.html',1,'ScoredProductions::StreamLinked::API']]],
  ['image_27',['Image',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_image.html',1,'ScoredProductions::StreamLinked::EventSub::Events::Objects']]],
  ['imageblock_28',['ImageBlock',['../struct_scored_productions_1_1_stream_linked_1_1_uni_gif_1_1_uni_gif_1_1_image_block.html',1,'ScoredProductions::StreamLinked::UniGif::UniGif']]],
  ['imagedatablock_29',['ImageDataBlock',['../struct_scored_productions_1_1_stream_linked_1_1_uni_gif_1_1_uni_gif_1_1_image_block_1_1_image_data_block.html',1,'ScoredProductions::StreamLinked::UniGif::UniGif::ImageBlock']]],
  ['imageheaderhelpers_30',['ImageHeaderHelpers',['../class_scored_productions_1_1_stream_linked_1_1_image_header_helpers.html',1,'ScoredProductions::StreamLinked']]],
  ['images_31',['Images',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_images.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['imoderation_32',['IModeration',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_i_moderation.html',1,'ScoredProductions::StreamLinked::API::Moderation']]],
  ['implicitgrantflow_33',['ImplicitGrantFlow',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_implicit_grant_flow.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['inoresponse_34',['INoResponse',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_no_response.html',1,'ScoredProductions::StreamLinked::API']]],
  ['internalsettingsstore_35',['InternalSettingsStore',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_internal_settings_store.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['iparsedmessage_36',['IParsedMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_parsed_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['ipoll_37',['IPoll',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_poll.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ipolls_38',['IPolls',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_polls_1_1_i_polls.html',1,'ScoredProductions::StreamLinked::API::Polls']]],
  ['iprediction_39',['IPrediction',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_prediction.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['ipredictions_40',['IPredictions',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_predictions_1_1_i_predictions.html',1,'ScoredProductions::StreamLinked::API::Predictions']]],
  ['iraids_41',['IRaids',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_raids_1_1_i_raids.html',1,'ScoredProductions::StreamLinked::API::Raids']]],
  ['irccommandtype_42',['IRCCommandType',['../class_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_extensions_1_1_i_r_c_command_type.html',1,'ScoredProductions::StreamLinked::IRC::Extensions']]],
  ['ischedule_43',['ISchedule',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_schedule_1_1_i_schedule.html',1,'ScoredProductions::StreamLinked::API::Schedule']]],
  ['iscope_44',['IScope',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_scopes_1_1_i_scope.html',1,'ScoredProductions::StreamLinked::API::Scopes']]],
  ['isearch_45',['ISearch',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search_1_1_i_search.html',1,'ScoredProductions::StreamLinked::API::Search']]],
  ['isendermessage_46',['ISenderMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_sender_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['ishared_47',['IShared',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_i_shared.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['isharedextensions_48',['ISharedExtensions',['../class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_i_shared_extensions.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['ishield_49',['IShield',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_shield.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['istreams_50',['IStreams',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_streams_1_1_i_streams.html',1,'ScoredProductions::StreamLinked::API::Streams']]],
  ['isubscription_51',['ISubscription',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_subscription.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['isubscriptions_52',['ISubscriptions',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_subscriptions_1_1_i_subscriptions.html',1,'ScoredProductions::StreamLinked::API::Subscriptions']]],
  ['itagcontainer_53',['ITagContainer',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_container.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_54',['ITagMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20clearchat_2etags_20_3e_55',['ITagMessage&lt; CLEARCHAT.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20clearmsg_2etags_20_3e_56',['ITagMessage&lt; CLEARMSG.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20globaluserstate_2etags_20_3e_57',['ITagMessage&lt; GLOBALUSERSTATE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20notice_2etags_20_3e_58',['ITagMessage&lt; NOTICE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20privmsg_2etags_20_3e_59',['ITagMessage&lt; PRIVMSG.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20roomstate_2etags_20_3e_60',['ITagMessage&lt; ROOMSTATE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20usernotice_2etags_20_3e_61',['ITagMessage&lt; USERNOTICE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['itagmessage_3c_20userstate_2etags_20_3e_62',['ITagMessage&lt; USERSTATE.TAGS &gt;',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_tag_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['iteams_63',['ITeams',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_teams_1_1_i_teams.html',1,'ScoredProductions::StreamLinked::API::Teams']]],
  ['itwitchapidataobject_64',['ITwitchAPIDataObject',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_twitch_a_p_i_data_object.html',1,'ScoredProductions::StreamLinked::API']]],
  ['itwitchapidataobjectextensions_65',['ITwitchAPIDataObjectExtensions',['../class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_twitch_a_p_i_data_object_extensions.html',1,'ScoredProductions::StreamLinked::API']]],
  ['itwitchircmessage_66',['ITwitchIRCMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_twitch_i_r_c_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['iuser_67',['IUser',['../interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_interfaces_1_1_i_user.html',1,'ScoredProductions::StreamLinked::EventSub::Interfaces']]],
  ['iuseraccesstoken_68',['IUserAccessToken',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_i_user_access_token.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['iusermessage_69',['IUserMessage',['../interface_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_interface_1_1_i_user_message.html',1,'ScoredProductions::StreamLinked::IRC::Message::Interface']]],
  ['iusers_70',['IUsers',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_users_1_1_i_users.html',1,'ScoredProductions::StreamLinked::API::Users']]],
  ['ivideos_71',['IVideos',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_videos_1_1_i_videos.html',1,'ScoredProductions::StreamLinked::API::Videos']]],
  ['iwhispers_72',['IWhispers',['../interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_whispers_1_1_i_whispers.html',1,'ScoredProductions::StreamLinked::API::Whispers']]]
];
