var searchData=
[
  ['saveclientdetails_0',['SaveClientDetails',['../class_scored_productions_1_1_stream_linked_1_1_save_client_details.html',1,'ScoredProductions::StreamLinked']]],
  ['searchcategories_1',['SearchCategories',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search_1_1_search_categories.html',1,'ScoredProductions::StreamLinked::API::Search']]],
  ['searchchannels_2',['SearchChannels',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search_1_1_search_channels.html',1,'ScoredProductions::StreamLinked::API::Search']]],
  ['secrets_3',['Secrets',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_i_extensions_1_1_secrets.html',1,'ScoredProductions::StreamLinked::API::Extensions::IExtensions']]],
  ['segment_4',['Segment',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_schedule_1_1_i_schedule_1_1_segment.html',1,'ScoredProductions::StreamLinked::API::Schedule::ISchedule']]],
  ['sendashoutout_5',['SendAShoutout',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_a_shoutout.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['sendchatannouncement_6',['SendChatAnnouncement',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_announcement.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['sendchatmessage_7',['SendChatMessage',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_message.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['sendextensionchatmessage_8',['SendExtensionChatMessage',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_send_extension_chat_message.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['sendextensionpubsubmessage_9',['SendExtensionPubSubMessage',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_send_extension_pub_sub_message.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['sendgueststarinvite_10',['SendGuestStarInvite',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star_1_1_send_guest_star_invite.html',1,'ScoredProductions::StreamLinked::API::Guest_Star']]],
  ['sendwhisper_11',['SendWhisper',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_whispers_1_1_send_whisper.html',1,'ScoredProductions::StreamLinked::API::Whispers']]],
  ['session_12',['Session',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_session.html',1,'ScoredProductions::StreamLinked::EventSub::WebSocketMessages']]],
  ['setextensionconfigurationsegment_13',['SetExtensionConfigurationSegment',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_set_extension_configuration_segment.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['setextensionrequiredconfiguration_14',['SetExtensionRequiredConfiguration',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_set_extension_required_configuration.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['shards_15',['Shards',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_shards.html',1,'ScoredProductions::StreamLinked::API::Conduits::IConduits']]],
  ['shieldmodebegin_16',['ShieldModeBegin',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_shield_mode_begin.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['shieldmodeend_17',['ShieldModeEnd',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_shield_mode_end.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['shoutoutcreate_18',['ShoutoutCreate',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_shoutout_create.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['shoutoutreceived_19',['ShoutoutReceived',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_shoutout_received.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['singletoninstance_20',['SingletonInstance',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20debugmanager_20_3e_21',['SingletonInstance&lt; DebugManager &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitchapiclient_20_3e_22',['SingletonInstance&lt; TwitchAPIClient &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitchbadgemanager_20_3e_23',['SingletonInstance&lt; TwitchBadgeManager &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitchemotemanager_20_3e_24',['SingletonInstance&lt; TwitchEmoteManager &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitcheventsubclient_20_3e_25',['SingletonInstance&lt; TwitchEventSubClient &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitchircclient_20_3e_26',['SingletonInstance&lt; TwitchIRCClient &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitchmessageatlasmanager_20_3e_27',['SingletonInstance&lt; TwitchMessageAtlasManager &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['size_28',['Size',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_bits_1_1_i_bits_1_1_size.html',1,'ScoredProductions::StreamLinked::API::Bits::IBits']]],
  ['slow_29',['Slow',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_slow.html',1,'ScoredProductions::StreamLinked::EventSub::IChannel']]],
  ['snoozenextad_30',['SnoozeNextAd',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads_1_1_snooze_next_ad.html',1,'ScoredProductions::StreamLinked::API::Ads']]],
  ['socketresponse_31',['SocketResponse',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_socket_response.html',1,'ScoredProductions::StreamLinked::EventSub::WebSocketMessages']]],
  ['startaraid_32',['StartARaid',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_raids_1_1_start_a_raid.html',1,'ScoredProductions::StreamLinked::API::Raids']]],
  ['startcommercial_33',['StartCommercial',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads_1_1_start_commercial.html',1,'ScoredProductions::StreamLinked::API::Ads']]],
  ['streamoffline_34',['StreamOffline',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_stream_offline.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['streamonline_35',['StreamOnline',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_stream_online.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['stringextensions_36',['StringExtensions',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_string_extensions.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['sub_37',['Sub',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_notification_1_1_sub.html',1,'ScoredProductions::StreamLinked::EventSub::Events::ChannelChatNotification']]],
  ['subgift_38',['SubGift',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_notification_1_1_sub_gift.html',1,'ScoredProductions::StreamLinked::EventSub::Events::ChannelChatNotification']]],
  ['subscription_39',['Subscription',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_subscription.html',1,'ScoredProductions::StreamLinked::EventSub::WebSocketMessages']]]
];
