var searchData=
[
  ['searchcategories_0',['SearchCategories',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search_1_1_search_categories.html',1,'ScoredProductions::StreamLinked::API::Search']]],
  ['searchchannels_1',['SearchChannels',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search_1_1_search_channels.html',1,'ScoredProductions::StreamLinked::API::Search']]],
  ['secrets_2',['Secrets',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_secrets.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['segment_3',['Segment',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_segment.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['sendashoutout_4',['SendAShoutout',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_a_shoutout.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['sendchatannouncement_5',['SendChatAnnouncement',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_announcement.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['sendchatmessage_6',['SendChatMessage',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_message.html',1,'ScoredProductions::StreamLinked::API::Chat']]],
  ['sendextensionchatmessage_7',['SendExtensionChatMessage',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_send_extension_chat_message.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['sendextensionpubsubmessage_8',['SendExtensionPubSubMessage',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_send_extension_pub_sub_message.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['sendgueststarinvite_9',['SendGuestStarInvite',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star_1_1_send_guest_star_invite.html',1,'ScoredProductions::StreamLinked::API::Guest_Star']]],
  ['sendwhisper_10',['SendWhisper',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_whispers_1_1_send_whisper.html',1,'ScoredProductions::StreamLinked::API::Whispers']]],
  ['serversettings_11',['ServerSettings',['../class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_server_settings.html',1,'ScoredProductions::StreamLinked::API::AuthContainers']]],
  ['session_12',['Session',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_session.html',1,'ScoredProductions::StreamLinked::EventSub::WebSocketMessages']]],
  ['setextensionconfigurationsegment_13',['SetExtensionConfigurationSegment',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_set_extension_configuration_segment.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['setextensionrequiredconfiguration_14',['SetExtensionRequiredConfiguration',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions_1_1_set_extension_required_configuration.html',1,'ScoredProductions::StreamLinked::API::Extensions']]],
  ['shards_15',['Shards',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_shards.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['shared_5fall_5ftime_5fhigh_16',['Shared_All_Time_High',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_shared___all___time___high.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['sharedtrainparticipants_17',['SharedTrainParticipants',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_shared_train_participants.html',1,'ScoredProductions::StreamLinked::EventSub::Events::Objects']]],
  ['singletonbase_18',['SingletonBase',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_base.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletondispatcher_19',['SingletonDispatcher',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_dispatcher.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletondispatcher_3c_20twitchbadgemanager_20_3e_20',['SingletonDispatcher&lt; TwitchBadgeManager &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_dispatcher.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletondispatcher_3c_20twitchemotemanager_20_3e_21',['SingletonDispatcher&lt; TwitchEmoteManager &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_dispatcher.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletondispatcher_3c_20twitcheventsubclient_20_3e_22',['SingletonDispatcher&lt; TwitchEventSubClient &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_dispatcher.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletondispatcher_3c_20twitchircclient_20_3e_23',['SingletonDispatcher&lt; TwitchIRCClient &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_dispatcher.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_24',['SingletonInstance',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20debugmanager_20_3e_25',['SingletonInstance&lt; DebugManager &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitchircmessagehistory_20_3e_26',['SingletonInstance&lt; TwitchIRCMessageHistory &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['singletoninstance_3c_20twitchmessageatlasproducer_20_3e_27',['SingletonInstance&lt; TwitchMessageAtlasProducer &gt;',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_singleton_instance.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['size_28',['Size',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_size.html',1,'ScoredProductions::StreamLinked::API::SharedContainers']]],
  ['slow_29',['Slow',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_slow.html',1,'ScoredProductions::StreamLinked::EventSub::Events::Objects']]],
  ['snoozenextad_30',['SnoozeNextAd',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads_1_1_snooze_next_ad.html',1,'ScoredProductions::StreamLinked::API::Ads']]],
  ['socketresponse_31',['SocketResponse',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_socket_response.html',1,'ScoredProductions::StreamLinked::EventSub::WebSocketMessages']]],
  ['startaraid_32',['StartARaid',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_raids_1_1_start_a_raid.html',1,'ScoredProductions::StreamLinked::API::Raids']]],
  ['startcommercial_33',['StartCommercial',['../struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads_1_1_start_commercial.html',1,'ScoredProductions::StreamLinked::API::Ads']]],
  ['streamoffline_34',['StreamOffline',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_stream_offline.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['streamonline_35',['StreamOnline',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_stream_online.html',1,'ScoredProductions::StreamLinked::EventSub::Events']]],
  ['stringbuilderprovider_36',['StringBuilderProvider',['../class_scored_productions_1_1_stream_linked_1_1_utility_1_1_string_builder_provider.html',1,'ScoredProductions::StreamLinked::Utility']]],
  ['stringpair_37',['StringPair',['../class_scored_productions_1_1_stream_linked_1_1_visual_scripting_1_1_string_pair.html',1,'ScoredProductions::StreamLinked::VisualScripting']]],
  ['stringpairunit_38',['StringPairUnit',['../class_scored_productions_1_1_stream_linked_1_1_visual_scripting_1_1_string_pair_unit.html',1,'ScoredProductions::StreamLinked::VisualScripting']]],
  ['sub_39',['Sub',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_sub.html',1,'ScoredProductions::StreamLinked::EventSub::Events::Objects']]],
  ['subgift_40',['SubGift',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_sub_gift.html',1,'ScoredProductions::StreamLinked::EventSub::Events::Objects']]],
  ['subscription_41',['Subscription',['../struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_subscription.html',1,'ScoredProductions::StreamLinked::EventSub::WebSocketMessages']]]
];
