var _assign_guest_star_slot_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Guest_Star.AssignGuestStarSlot", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_guest___star_1_1_assign_guest_star_slot.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_guest___star_1_1_assign_guest_star_slot" ]
];