var _charity_campaign_start_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.Events.CharityCampaignStart", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_charity_campaign_start.html", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_charity_campaign_start" ]
];