var _channel_points_custom_reward_update_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.Events.ChannelPointsCustomRewardUpdate", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_update.html", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_update" ]
];