var _channel_guest_star_settings_update_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.Events.ChannelGuestStarSettingsUpdate", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_guest_star_settings_update.html", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_guest_star_settings_update" ]
];