var _channel_points_custom_reward_redemption_update_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.Events.ChannelPointsCustomRewardRedemptionUpdate", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_redemption_update.html", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_redemption_update" ]
];