var _charity_campaign_progress_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.Events.CharityCampaignProgress", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_charity_campaign_progress.html", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_charity_campaign_progress" ]
];