var _channel_subscription_gift_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.Events.ChannelSubscriptionGift", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_subscription_gift.html", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_events_1_1_channel_subscription_gift" ]
];