var _create_custom_rewards_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Channel_Points.CreateCustomRewards", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_channel___points_1_1_create_custom_rewards.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_channel___points_1_1_create_custom_rewards" ]
];