var _delete_custom_rewards_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Channel_Points.DeleteCustomReward", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_channel___points_1_1_delete_custom_reward.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_channel___points_1_1_delete_custom_reward" ]
];