var _delete_channel_stream_schedule_segment_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Schedule.DeleteChannelStreamScheduleSegment", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_schedule_1_1_delete_channel_stream_schedule_segment.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_schedule_1_1_delete_channel_stream_schedule_segment" ]
];