var _device_code_grant_flow_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.AuthContainers.DeviceCodeGrantFlow", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_auth_containers_1_1_device_code_grant_flow.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_auth_containers_1_1_device_code_grant_flow" ],
    [ "ScoredProductions.TwitchUnited.API.AuthContainers.DeviceCodeGrantFlow.RetrievalSettings", "class_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_auth_containers_1_1_device_code_grant_flow_1_1_retrieval_settings.html", "class_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_auth_containers_1_1_device_code_grant_flow_1_1_retrieval_settings" ]
];