var _event_sub_information_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.ExtensionAttributes.EventSubInformation", "class_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information.html", "class_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information" ],
    [ "ScoredProductions.TwitchUnited.EventSub.ExtensionAttributes.EventSubInformationExtensions", "class_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_extensions.html", "class_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_extensions" ]
];