var _get_guest_star_invites_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Guest_Star.GetGuestStarInvites", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_guest___star_1_1_get_guest_star_invites.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_guest___star_1_1_get_guest_star_invites" ]
];