var _i_conduits_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Conduits.IConduits", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits.html", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits" ],
    [ "ScoredProductions.TwitchUnited.API.Conduits.IConduits.Transport", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_transport.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_transport" ],
    [ "ScoredProductions.TwitchUnited.API.Conduits.IConduits.Shards", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_shards.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_shards" ],
    [ "ScoredProductions.TwitchUnited.API.Conduits.IConduits.Shards.Transport", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_shards_1_1_transport.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_shards_1_1_transport" ],
    [ "ScoredProductions.TwitchUnited.API.Conduits.IConduits.Errors", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_errors.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_conduits_1_1_i_conduits_1_1_errors" ]
];