var _max_per_user_per_stream_8cs =
[
    [ "ScoredProductions.TwitchUnited.EventSub.Common.MaxPerUserPerStream", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_common_1_1_max_per_user_per_stream.html", "struct_scored_productions_1_1_twitch_united_1_1_event_sub_1_1_common_1_1_max_per_user_per_stream" ]
];