var _remove_channel_moderator_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Moderation.RemoveChannelModerator", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_moderation_1_1_remove_channel_moderator.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_moderation_1_1_remove_channel_moderator" ]
];