var _set_extension_configuration_segment_8cs =
[
    [ "ScoredProductions.TwitchUnited.API.Extensions.SetExtensionConfigurationSegment", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_extensions_1_1_set_extension_configuration_segment.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_extensions_1_1_set_extension_configuration_segment" ]
];