var _twitch_message_atlas_manager_8cs =
[
    [ "ScoredProductions.TwitchUnited.ManagersAndBuilders.TwitchMessageAtlasManager", "class_scored_productions_1_1_twitch_united_1_1_managers_and_builders_1_1_twitch_message_atlas_manager.html", "class_scored_productions_1_1_twitch_united_1_1_managers_and_builders_1_1_twitch_message_atlas_manager" ]
];