var namespace_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_analytics =
[
    [ "GetExtensionAnalytics", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_analytics_1_1_get_extension_analytics.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_analytics_1_1_get_extension_analytics" ],
    [ "GetGameAnalytics", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_analytics_1_1_get_game_analytics.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_analytics_1_1_get_game_analytics" ],
    [ "IAnalytics", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_analytics_1_1_i_analytics.html", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_analytics_1_1_i_analytics" ]
];