var namespace_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits =
[
    [ "GetBitsLeaderboard", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_get_bits_leaderboard.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_get_bits_leaderboard" ],
    [ "GetCheermotes", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_get_cheermotes.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_get_cheermotes" ],
    [ "GetExtensionTransactions", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_get_extension_transactions.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_get_extension_transactions" ],
    [ "IBits", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_i_bits.html", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_bits_1_1_i_bits" ]
];