var namespace_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points =
[
    [ "CreateCustomRewards", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_create_custom_rewards.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_create_custom_rewards" ],
    [ "DeleteCustomReward", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_delete_custom_reward.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_delete_custom_reward" ],
    [ "GetCustomReward", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_get_custom_reward.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_get_custom_reward" ],
    [ "GetCustomRewardRedemption", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_get_custom_reward_redemption.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_get_custom_reward_redemption" ],
    [ "IChannel_Points", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_i_channel___points.html", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_i_channel___points" ],
    [ "UpdateCustomReward", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_update_custom_reward.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_update_custom_reward" ],
    [ "UpdateRedemptionStatus", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_update_redemption_status.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_channel___points_1_1_update_redemption_status" ]
];