var namespace_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_extension_attributes =
[
    [ "EventSubInformation", "class_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information.html", "class_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information" ],
    [ "EventSubInformationExtensions", "class_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_extensions.html", "class_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_extensions" ]
];