var namespace_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub =
[
    [ "CreateEventSubSubscription", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_create_event_sub_subscription.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_create_event_sub_subscription" ],
    [ "DeleteEventSubSubscription", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_delete_event_sub_subscription.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_delete_event_sub_subscription" ],
    [ "GetEventSubSubscriptions", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_get_event_sub_subscriptions.html", "struct_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_get_event_sub_subscriptions" ],
    [ "IEventSub", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_i_event_sub.html", "interface_scored_productions_1_1_twitch_united_1_1_a_p_i_1_1_event_sub_1_1_i_event_sub" ]
];