var namespace_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects =
[
    [ "BitsVoting", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_bits_voting.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_bits_voting" ],
    [ "Condition", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_condition.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_condition" ],
    [ "Emotes", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_emotes.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_emotes" ],
    [ "GlobalCooldown", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_global_cooldown.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_objects_1_1_global_cooldown" ]
];