var namespace_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits =
[
    [ "CreateConduits", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_create_conduits.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_create_conduits" ],
    [ "DeleteConduits", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_delete_conduits.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_delete_conduits" ],
    [ "GetConduits", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_get_conduits.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_get_conduits" ],
    [ "GetConduitShards", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_get_conduit_shards.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_get_conduit_shards" ],
    [ "IConduits", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_i_conduits.html", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_i_conduits" ],
    [ "UpdateConduits", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_update_conduits.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_update_conduits" ],
    [ "UpdateConduitShards", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_update_conduit_shards.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_conduits_1_1_update_conduit_shards" ]
];