var _authorization_code_grant_flow_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.AuthContainers.AuthorizationCodeGrantFlow", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_auth_containers_1_1_authorization_code_grant_flow.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_auth_containers_1_1_authorization_code_grant_flow" ]
];