var _channel_points_custom_reward_add_8cs =
[
    [ "ScoredProductions.TwitchUnite.EventSub.Events.ChannelPointsCustomRewardAdd", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_add.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_points_custom_reward_add" ]
];