var _channel_guest_star_guest_update_8cs =
[
    [ "ScoredProductions.TwitchUnite.EventSub.Events.ChannelGuestStarGuestUpdate", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_guest_star_guest_update.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_guest_star_guest_update" ]
];