var _channel_subscription_message_8cs =
[
    [ "ScoredProductions.TwitchUnite.EventSub.Events.ChannelSubscriptionMessage", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_subscription_message.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_channel_subscription_message" ]
];