var _check_user_subscription_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.Subscriptions.CheckUserSubscription", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_subscriptions_1_1_check_user_subscription.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_subscriptions_1_1_check_user_subscription" ]
];