var _client_credentials_flow_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.AuthContainers.ClientCredentialsFlow", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_auth_containers_1_1_client_credentials_flow.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_auth_containers_1_1_client_credentials_flow" ]
];