var _get_drops_entitlements_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.Entitlements.GetDropsEntitlements", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_get_drops_entitlements.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_get_drops_entitlements" ]
];