var _get_content_classification_labels_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.CCLs.GetContentClassificationLabels", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_c_c_ls_1_1_get_content_classification_labels.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_c_c_ls_1_1_get_content_classification_labels" ]
];