var _i_guest___star_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.Guest_Star.IGuest_Star", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star.html", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star" ],
    [ "ScoredProductions.TwitchUnite.API.Guest_Star.IGuest_Star.AudioSettings", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star_1_1_audio_settings.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star_1_1_audio_settings" ],
    [ "ScoredProductions.TwitchUnite.API.Guest_Star.IGuest_Star.VideoSettings", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star_1_1_video_settings.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star_1_1_video_settings" ],
    [ "ScoredProductions.TwitchUnite.API.Guest_Star.IGuest_Star.Guest", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star_1_1_guest.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_guest___star_1_1_i_guest___star_1_1_guest" ]
];