var _i_user_access_token_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.AuthContainers.IUserAccessToken", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_auth_containers_1_1_i_user_access_token.html", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_auth_containers_1_1_i_user_access_token" ]
];