var _socket_responce_8cs =
[
    [ "ScoredProductions.TwitchUnite.EventSub.WebSocketMessages.SocketResponse", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_web_socket_messages_1_1_socket_response.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_web_socket_messages_1_1_socket_response" ]
];