var _twitch_event_sub_conditions_8cs =
[
    [ "ScoredProductions.TwitchUnite.EventSub.WebSocketMessages.TwitchEventSubConditions", "class_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_web_socket_messages_1_1_twitch_event_sub_conditions.html", "class_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_web_socket_messages_1_1_twitch_event_sub_conditions" ]
];