var _update_auto_mod_settings_8cs =
[
    [ "ScoredProductions.TwitchUnite.API.Moderation.UpdateAutoModSettings", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_moderation_1_1_update_auto_mod_settings.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_moderation_1_1_update_auto_mod_settings" ]
];