var _user_authorization_revoke_8cs =
[
    [ "ScoredProductions.TwitchUnite.EventSub.Events.UserAuthorizationRevoke", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_user_authorization_revoke.html", "struct_scored_productions_1_1_twitch_unite_1_1_event_sub_1_1_events_1_1_user_authorization_revoke" ]
];