var namespace_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements =
[
    [ "GetDropsEntitlements", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_get_drops_entitlements.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_get_drops_entitlements" ],
    [ "IEntitlements", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_i_entitlements.html", "interface_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_i_entitlements" ],
    [ "UpdateDropsEntitlements", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_update_drops_entitlements.html", "struct_scored_productions_1_1_twitch_unite_1_1_a_p_i_1_1_entitlements_1_1_update_drops_entitlements" ]
];