var _add_suspicious_status_to_chat_user_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Moderation.AddSuspiciousStatusToChatUser", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_add_suspicious_status_to_chat_user.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_add_suspicious_status_to_chat_user" ]
];