var _automod_settings_update_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.AutomodSettingsUpdate", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_automod_settings_update.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_automod_settings_update" ]
];