var _automod_message_update_v2_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.AutomodMessageUpdateV2", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_automod_message_update_v2.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_automod_message_update_v2" ]
];