var _channel_suspicious_user_message_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelSuspiciousUserUpdate", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_suspicious_user_update.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_suspicious_user_update" ]
];