var _channel_charity_donation_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelCharityDonation", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_charity_donation.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_charity_donation" ]
];