var _channel_goals_progress_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelGoalsProgress", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_goals_progress.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_goals_progress" ]
];