var _channel_shoutout_received_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelShoutoutReceived", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_shoutout_received.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_shoutout_received" ]
];