var _channel_charity_campaign_stop_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelCharityCampaignStop", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_charity_campaign_stop.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_charity_campaign_stop" ]
];