var _channel_points_voting_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.Objects.ChannelPointsVoting", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_channel_points_voting.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_channel_points_voting" ]
];