var _channel_moderator_remove_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelModeratorRemove", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_moderator_remove.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_moderator_remove" ]
];