var _channel_hype_train_progress_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelHypeTrainProgress", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_hype_train_progress.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_hype_train_progress" ]
];