var _channel_chat_notification_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelChatNotification", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_notification.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_notification" ]
];