var _channel_points_automatic_reward_redemption_v2_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelPointsAutomaticRewardRedemptionV2", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_points_automatic_reward_redemption_v2.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_points_automatic_reward_redemption_v2" ]
];