var _channel_chat_settings_update_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.ChannelChatSettingsUpdate", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_settings_update.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_channel_chat_settings_update" ]
];