var _community_sub_gift_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.Objects.CommunitySubGift", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_community_sub_gift.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_community_sub_gift" ]
];