var _continuation_settings_8cs =
[
    [ "ScoredProductions.StreamLinked.API.AuthContainers.ContinuationSettings", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_continuation_settings.html", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers_1_1_continuation_settings" ]
];