var _delete_guest_star_slot_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Guest_Star.DeleteGuestStarSlot", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star_1_1_delete_guest_star_slot.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star_1_1_delete_guest_star_slot" ]
];