var _delete_event_sub_subscription_8cs =
[
    [ "ScoredProductions.StreamLinked.API.EventSub.DeleteEventSubSubscription", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub_1_1_delete_event_sub_subscription.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub_1_1_delete_event_sub_subscription" ]
];