var _event_sub_information_attribute_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.ExtensionAttributes.EventSubInformationAttribute", "class_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_attribute.html", "class_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_attribute" ],
    [ "ScoredProductions.StreamLinked.EventSub.ExtensionAttributes.EventSubInformationExtensions", "class_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_extensions.html", "class_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_extension_attributes_1_1_event_sub_information_extensions" ]
];