var _g_l_o_b_a_l_u_s_e_r_s_t_a_t_e_8cs =
[
    [ "ScoredProductions.StreamLinked.IRC.Message.GLOBALUSERSTATE", "struct_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_g_l_o_b_a_l_u_s_e_r_s_t_a_t_e.html", "struct_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_g_l_o_b_a_l_u_s_e_r_s_t_a_t_e" ],
    [ "ScoredProductions.StreamLinked.IRC.Message.GLOBALUSERSTATE.TAGS", "struct_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_g_l_o_b_a_l_u_s_e_r_s_t_a_t_e_1_1_t_a_g_s.html", "struct_scored_productions_1_1_stream_linked_1_1_i_r_c_1_1_message_1_1_g_l_o_b_a_l_u_s_e_r_s_t_a_t_e_1_1_t_a_g_s" ]
];