var _get_event_sub_subscriptions_8cs =
[
    [ "ScoredProductions.StreamLinked.API.EventSub.GetEventSubSubscriptions", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub_1_1_get_event_sub_subscriptions.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub_1_1_get_event_sub_subscriptions" ]
];