var _get_charity_campaign_donations_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Charity.GetCharityCampaignDonations", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_charity_1_1_get_charity_campaign_donations.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_charity_1_1_get_charity_campaign_donations" ]
];