var _gift_paid_upgrade_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.Objects.GiftPaidUpgrade", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_gift_paid_upgrade.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_gift_paid_upgrade" ]
];