var _global___cooldown___setting_8cs =
[
    [ "ScoredProductions.StreamLinked.API.SharedContainers.Global_Cooldown_Setting", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_global___cooldown___setting.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_global___cooldown___setting" ]
];