var _i_channel___points_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Channel_Points.IChannel_Points", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channel___points_1_1_i_channel___points.html", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channel___points_1_1_i_channel___points" ]
];