var _json_serialization_exception_8cs =
[
    [ "ScoredProductions.StreamLinked.LightJson.Serialization.JsonSerializationException", "class_scored_productions_1_1_stream_linked_1_1_light_json_1_1_serialization_1_1_json_serialization_exception.html", "class_scored_productions_1_1_stream_linked_1_1_light_json_1_1_serialization_1_1_json_serialization_exception" ]
];