var _max_per_user_per_stream_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.Objects.MaxPerUserPerStream", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_max_per_user_per_stream.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_objects_1_1_max_per_user_per_stream" ]
];