var _modify_channel_information_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Channels.ModifyChannelInformation", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channels_1_1_modify_channel_information.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channels_1_1_modify_channel_information" ]
];