var _socket_responce_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.WebSocketMessages.SocketResponse", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_socket_response.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_web_socket_messages_1_1_socket_response" ]
];