var _twitch_a_p_i_client_8_make_twitch_a_p_i_request_8cs =
[
    [ "ScoredProductions.StreamLinked.API.TwitchAPIClient", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_client.html", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_client" ],
    [ "ScoredProductions.StreamLinked.API.TwitchAPIClient.MakeTwitchAPIRequestSettings", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_client_1_1_make_twitch_a_p_i_request_settings.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_client_1_1_make_twitch_a_p_i_request_settings" ]
];