var _twitch_event_sub_scope_attribute_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Scopes.TwitchEventSubScopeAttribute", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_scopes_1_1_twitch_event_sub_scope_attribute.html", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_scopes_1_1_twitch_event_sub_scope_attribute" ]
];