var _twitch_badge_manager_8cs =
[
    [ "ScoredProductions.StreamLinked.ManagersAndBuilders.TwitchBadgeManager", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_twitch_badge_manager.html", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_twitch_badge_manager" ]
];