var _twitch_badge_8cs =
[
    [ "ScoredProductions.StreamLinked.ManagersAndBuilders.TwitchBadge", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_twitch_badge.html", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_twitch_badge" ],
    [ "ScoredProductions.StreamLinked.ManagersAndBuilders.TwitchBadge.Version", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_twitch_badge_1_1_version.html", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_twitch_badge_1_1_version" ]
];