var _twitch_a_p_i_2_a_p_i_endpoints_2_shared_containers_2_transport_8cs =
[
    [ "ScoredProductions.StreamLinked.API.SharedContainers.Transport", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_transport.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_shared_containers_1_1_transport" ]
];