var _update_shield_mode_status_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Moderation.UpdateShieldModeStatus", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_update_shield_mode_status.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_update_shield_mode_status" ]
];