var _update_channel_stream_schedule_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Schedule.UpdateChannelStreamSchedule", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_schedule_1_1_update_channel_stream_schedule.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_schedule_1_1_update_channel_stream_schedule" ]
];