var _update_auto_mod_settings_8cs =
[
    [ "ScoredProductions.StreamLinked.API.Moderation.UpdateAutoModSettings", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_update_auto_mod_settings.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation_1_1_update_auto_mod_settings" ]
];