var _user_authorization_revoke_8cs =
[
    [ "ScoredProductions.StreamLinked.EventSub.Events.UserAuthorizationRevoke", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_user_authorization_revoke.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_events_1_1_user_authorization_revoke" ]
];