var interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel =
[
    [ "AutomodTerms", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_automod_terms.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_automod_terms" ],
    [ "Badges", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_badges.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_badges" ],
    [ "Ban", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_ban.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_ban" ],
    [ "Delete", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_delete.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_delete" ],
    [ "Followers", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_followers.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_followers" ],
    [ "Message", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_message.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_message" ],
    [ "Mod", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_mod.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_mod" ],
    [ "Raid", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_raid.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_raid" ],
    [ "Slow", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_slow.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_slow" ],
    [ "Timeout", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_timeout.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_timeout" ],
    [ "Unban", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unban.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unban" ],
    [ "UnbanRequest", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unban_request.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unban_request" ],
    [ "Unmod", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unmod.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unmod" ],
    [ "Unraid", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unraid.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unraid" ],
    [ "Untimeout", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_untimeout.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_untimeout" ],
    [ "Unvip", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unvip.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_unvip" ],
    [ "Vip", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_vip.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_vip" ],
    [ "Warn", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_warn.html", "struct_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel_1_1_warn" ],
    [ "broadcaster_user_id", "interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel.html#a48117cefb304fdebbbc4a46ddad8e07f", null ],
    [ "broadcaster_user_login", "interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel.html#a2c6c983d34855cc60fe39e7624b8aae1", null ],
    [ "broadcaster_user_name", "interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel.html#a1fcc0f31a77656f1b7716e4fb019df85", null ],
    [ "Enum", "interface_scored_productions_1_1_stream_linked_1_1_event_sub_1_1_i_channel.html#a2d17722ac8ae3714d9ae38f83172f874", null ]
];