var namespace_scored_productions_1_1_stream_linked_1_1_a_p_i =
[
    [ "Ads", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_ads" ],
    [ "Analytics", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_analytics.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_analytics" ],
    [ "Auth", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth" ],
    [ "AuthContainers", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_containers" ],
    [ "Bits", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_bits.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_bits" ],
    [ "CCLs", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_c_c_ls.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_c_c_ls" ],
    [ "Channel_Points", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channel___points.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channel___points" ],
    [ "Channels", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channels.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_channels" ],
    [ "Charity", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_charity.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_charity" ],
    [ "Chat", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat" ],
    [ "Clips", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_clips.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_clips" ],
    [ "Conduits", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_conduits.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_conduits" ],
    [ "Entitlements", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_entitlements.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_entitlements" ],
    [ "EventSub", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_event_sub" ],
    [ "Extensions", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_extensions" ],
    [ "Games", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_games.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_games" ],
    [ "Goals", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_goals.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_goals" ],
    [ "Guest_Star", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_guest___star" ],
    [ "Hype_Train", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_hype___train.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_hype___train" ],
    [ "Moderation", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_moderation" ],
    [ "Polls", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_polls.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_polls" ],
    [ "Predictions", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_predictions.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_predictions" ],
    [ "Raids", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_raids.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_raids" ],
    [ "Schedule", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_schedule.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_schedule" ],
    [ "Search", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_search" ],
    [ "Streams", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_streams.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_streams" ],
    [ "Subscriptions", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_subscriptions.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_subscriptions" ],
    [ "Teams", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_teams.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_teams" ],
    [ "Users", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_users.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_users" ],
    [ "Videos", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_videos.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_videos" ],
    [ "Whispers", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_whispers.html", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_whispers" ],
    [ "INoResponse", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_no_response.html", null ],
    [ "ITwitchAPIDataObject", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_twitch_a_p_i_data_object.html", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_i_twitch_a_p_i_data_object" ],
    [ "TwitchAPIClient", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_client.html", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_client" ],
    [ "TwitchAPIDataContainer", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_data_container.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_data_container" ],
    [ "TwitchAPILinks", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_links.html", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_a_p_i_links" ],
    [ "TwitchScopes", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_scopes.html", "class_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_twitch_scopes" ],
    [ "TwitchAPIRequestMethod", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i.html#a5e7fd0dcd52a1025215773db0142fae9", [
      [ "POST", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i.html#a5e7fd0dcd52a1025215773db0142fae9aa02439ec229d8be0e74b0c1602392310", null ],
      [ "GET", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i.html#a5e7fd0dcd52a1025215773db0142fae9a7528035a93ee69cedb1dbddb2f0bfcc8", null ],
      [ "PUT", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i.html#a5e7fd0dcd52a1025215773db0142fae9a3e75383a5992a6d15fb81e872e46e256", null ],
      [ "DELETE", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i.html#a5e7fd0dcd52a1025215773db0142fae9a32f68a60cef40faedbc6af20298c1a1e", null ],
      [ "PATCH", "namespace_scored_productions_1_1_stream_linked_1_1_a_p_i.html#a5e7fd0dcd52a1025215773db0142fae9a63bc9a3997d66d835d9f3ec29451407d", null ]
    ] ]
];