var namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat =
[
    [ "GetChannelChatBadges", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_channel_chat_badges.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_channel_chat_badges" ],
    [ "GetChannelEmotes", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_channel_emotes.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_channel_emotes" ],
    [ "GetChatSettings", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_chat_settings.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_chat_settings" ],
    [ "GetChatters", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_chatters.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_chatters" ],
    [ "GetEmoteSets", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_emote_sets.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_emote_sets" ],
    [ "GetGlobalChatBadges", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_global_chat_badges.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_global_chat_badges" ],
    [ "GetGlobalEmotes", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_global_emotes.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_global_emotes" ],
    [ "GetSharedChatSession", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_shared_chat_session.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_shared_chat_session" ],
    [ "GetUserChatColor", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_user_chat_color.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_user_chat_color" ],
    [ "GetUserEmotes", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_user_emotes.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_get_user_emotes" ],
    [ "IChat", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_i_chat.html", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_i_chat" ],
    [ "SendAShoutout", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_a_shoutout.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_a_shoutout" ],
    [ "SendChatAnnouncement", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_announcement.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_announcement" ],
    [ "SendChatMessage", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_message.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_send_chat_message" ],
    [ "UpdateChatSettings", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_update_chat_settings.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_update_chat_settings" ],
    [ "UpdateUserChatColor", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_update_user_chat_color.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_chat_1_1_update_user_chat_color" ]
];