var namespace_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth =
[
    [ "GetAuthorizationCodeToken", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_authorization_code_token.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_authorization_code_token" ],
    [ "GetClientCredentialsGrantFlow", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_client_credentials_grant_flow.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_client_credentials_grant_flow" ],
    [ "GetDeviceCodeGrantAuthorisation", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_device_code_grant_authorisation.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_device_code_grant_authorisation" ],
    [ "GetDeviceCodeGrantFlow", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_device_code_grant_flow.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_device_code_grant_flow" ],
    [ "GetTokenRefresh", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_token_refresh.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_token_refresh" ],
    [ "GetValidatedTokenInfo", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_validated_token_info.html", "struct_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_get_validated_token_info" ],
    [ "IAppAccess", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_app_access.html", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_app_access" ],
    [ "IAuth", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_auth.html", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_auth" ],
    [ "IUserAccess", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_user_access.html", "interface_scored_productions_1_1_stream_linked_1_1_a_p_i_1_1_auth_1_1_i_user_access" ]
];