var namespace_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers =
[
    [ "EmoteExtensions", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_emote_extensions.html", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_emote_extensions" ],
    [ "QueueContainer", "struct_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_queue_container.html", "struct_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_queue_container" ],
    [ "TwitchBadge", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_twitch_badge.html", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_twitch_badge" ],
    [ "TwitchEmote", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_twitch_emote.html", "class_scored_productions_1_1_stream_linked_1_1_managers_and_builders_1_1_containers_1_1_twitch_emote" ]
];